import Head from "next/head";
import "tailwindcss/tailwind.css";

// local components
import AboutComponent from "@/components/About";

const About = () => {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container m-10">
        <AboutComponent />
      </main>
    </>
  );
};

export default About;
